### ISSUE TITLE
[BUG] Build on Alpine docker image constant : 4294967295 overflows int

### ISSUE THREAD

**Issue by hugoglt** [unidoc/unipdf#112]
## Description

When I build a project with unipdf on docker alpine image it doesn't work

Dockerfile : 
```
FROM golang:alpine as builder
...
RUN glide install

RUN env GOOS=linux GOARCH=386 go build -v -o ordoclic-prescription-service cmd/main.go
...
```

to add the dependencies I tried 3 case in my `glide.yaml` file 

- package: github.com/unidoc/unipdf/v3
- package: github.com/unidoc/unipdf/...
- package: github.com/unidoc/unidoc/...

the error returned when the docker image is built is : 

```
...
# gitlab....fr/back/.../vendor/github.com/unidoc/unidoc/pdf/model
vendor/github.com/unidoc/unidoc/pdf/model/writer.go:538:12: constant 4294967295 overflows int
...
The command '/bin/sh -c env GOOS=linux GOARCH=386 go build -v -o ordoclic-prescription-service cmd/main.go' returned a non-zero code: 2
```

## Expected Behavior
Build not failed on alpine, so found unidoc version in 32 bit.

## Actual Behavior
1. Go to project with unidoc
2. docker build  -t test . -f dockerfiles/Dockerfile

## Attachments

I already looking for on internet I found nothing on this errors, just this : 
<img width="708" alt="Capture d’écran 2019-07-08 à 15 42 46" src="https://user-images.githubusercontent.com/36779248/60796118-12db3400-a197-11e9-841c-6261e764f0fb.png">

but it return an 404 error code

I don't search a method to build with 64 bit version system, thank you for your support.

**Comment by adrg** [comment]
@hugoglt Thank you for reporting the problem.

Unfortunately, `glide` seems to be mostly unmaintained and has some problems handling go module dependencies. Is it possible for you to use `go modules` instead of `glide` in order to use the latest version of `unipdf`?

A sample `go.mod` file:

```
module ordoclic-prescription-service

require (
	github.com/unidoc/unipdf/v3 v3.0.3
)
```

Otherwise, the only other solution would be to use `unidoc` instead of `unidpf`, but the `v3` branch instead of `master`. 

One of the following package configurations should work in `glide.yaml`:

```
- package: github.com/unidoc/unidoc
  version: v3
```

or

```
- package: github.com/unidoc/unidoc
  version: 1046d827446578bdad81621052d0a59d016e4a7c
```

**Comment by gunnsth** [comment]
Closing.  Note that github.com/unidoc/unidoc is not maintained so would recommend going with Go modules.
