### ISSUE TITLE
[BUG] Fill and flatten forms in the template file created with Adobe Acrobat Pro

### ISSUE THREAD

**Issue by schooltech** [unidoc/unipdf#200]
When you need to make different templates frequently, you will choose to complete the template creation in Adobe Acrobat Pro, which is more convenient. So I used Adobe Acrobat Pro to create a template, and then used unipdf to fill the fields' value. When there is Chinese to fill, nothing is filled, only blank, of course English and numbers are still displayed, I tried Adobe Acrobat Pro. Changing the font of the field does not help. 
I debug the unipdf code and found when strings are convert to utf16 string then return garbled in the func strutils.StringToUTF16(s)  and the code is as below:

`func StringToUTF16(s string) string {
	encoded := utf16.Encode([]rune(s))
	var buf bytes.Buffer
	for _, code := range encoded {
		buf.WriteByte(byte((code >> 8) & 0xff))
		buf.WriteByte(byte(code & 0xff))
	}
	return buf.String()
}`

I also try fill the template generated with unipdf, and the same with templates created with adobe acrobate pro.

Best regards,
David

[template.pdf](https://github.com/unidoc/unipdf/files/3878884/template.pdf)
![outpdf](https://user-images.githubusercontent.com/16329726/69415806-41c20300-0d50-11ea-9bef-be094dd346b6.png)

**Comment by gunnsth** [comment]
@schooltech Can you please post a self-contained example, including the source code and PDF that we can simply run and reproduce the issue?

**Comment by schooltech** [comment]
[unipdf_form_example.zip](https://github.com/unidoc/unipdf/files/3882041/unipdf_form_example.zip)

**Comment by gunnsth** [comment]
@schooltech We have prepared a fix that addresses this issue: https://github.com/unidoc/unipdf/pull/203
It has been merged into our development branch so please give it a try.

For it to work, you need to prepare your template such that a Chinese font is selected. This can be done in Acrobat by editing the field properties under appearance.
The problem previously was that when the Chinese font was selected, there was a problem with encodings that has been solved in #203.

The font that is otherwise selected is Helvetica, which does not have Chinese glyphs. In the future we would like to create a way to switch the font when filling and flattening fonts, but we will create a separate issue for that going forward.

**Comment by schooltech** [comment]
It works now, thanks a lot
