### ISSUE TITLE
Style guide additions - section comments and package names, imports

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unipdf#208]
Add two new items:

## 22. Section comments.
Section comments are comments that denote a section within a Go source code file.  They typically come before a series of related declarations or functions.

Those should be declared starting with an empty line, and one line with just `//` then the comment describing the section/group and another `//` followed by an empty line.

The section comment itself is typically a title and does not need to end with a period.

Example:
```go
// Context defines operations for rendering to a particular target.
type Context interface {
	//
	// Graphics state operations
	//

	// Push adds the current context state on the stack.
	Push()

	// Pop removes the most recent context state from the stack.
	Pop()

	//
	// Matrix operations
	//

	// Matrix returns the current transformation matrix.
	Matrix() transform.Matrix

	// SetMatrix modifies the transformation matrix.
	SetMatrix(m transform.Matrix)
```

If the section comment follows an opening bracket, a newline before can be omitted:
```go
switch op.Operand {
	//
	// Graphics stage operators
	//

	// Push current graphics state to the stack.
	case "q":
		ctx.Push()
	// Pop graphics state from the stack.
	case "Q":
		ctx.Pop()
```

## 23. Package naming guidelines.
Package names are important for at least 2 reasons:
- They are the first thing that the user sees when encountering a package
- They are the text that the user needs to type every time when they use the package

Therefore:
- They should give some context about what the package contains.
- They should not be too short or generic that they conflict with variable names or that it is likely that there are many packages with the same name.
- Since the namespace is only double layered, i.e. `package.Export`, it makes sense that the user should get some idea of the context from the package name.
- Package names should not be too cumbersome that users would want to use package aliases.

In general, package naming is nontrivial and those only serve as guidelines, whereas a good package name comes from insight as well.

## 24. Avoid package aliases imports.
This expands upon the previous section.

Avoid using package aliases in imports when importing packages with exactly the same name.
E.g. only in cases such as:
```go
import (
  aimage "a/image"
  bimage "b/image"
)
```
would be acceptable.  If package under `a/image` was considered more default or more used, it would be recommended to do
```go
import (
  "a/image"
  bimage "b/image"
)
```

Generally, prefer
```go
import (
  "f/somepackage"
)
```
over
```go
import (
  somepkg "f/somepackage"
)
```

We should rather create package names that are nice to import and use.

In the unlikely case that an external dependency package has a really generic name that conflicts with many variables in our code, we may consider a type alias.  Or if it has a really bad name that says nothing about the package contents (although, I doubt we would ever use such a package).

**Comment by adrg** [comment]
Looks good. Here is my view on each of the points:

23. Section comments can be useful when the code cannot be split using other methods. However, they should be used only where necessary. For example, if a file has lot of functions and they can be grouped by functionality, it might be better to group them into separate files, rather than using section comments.

24. I agree that package names should not be too short and that they should provide some context about their content. On the other hand, because the user has to write the name of the package every time, the names should not be too long either. Making package names too long will only result in user wanting to create aliases, in order to type less.
Moreover, the content of the package should be taken into consideration when choosing then name, as to avoid unnecessary redundancy naming-wise when creating the exported entities. For example, `render.ImageRenderer` is pretty redundant and should be avoided in my opinion. In this case, maybe the package should be called `image` so that it would allow `image.Renderer`. Another alternative would be to keep the render package and call the entity inside `ImageDevice` or `ImageContext`. I guess my point is that the content should decide the name of the package and not the other way around because otherwise a lot of time will be spent on trying to decide how to name exported entities such that they do not look cumbersome in relation to the package name.

25. I think the guidelines look good. Nothing to add here.

**Comment by gunnsth** [comment]
I am not sure. If a package is called image one kinda expects that it can load an image and work with images?  It feels like the purpose of the package should be reflected in the name as well.

I think it's impossible to completely avoid repetition, for example `image.Image` interface.  `render.Render` might be an option, I think the image is just an output from rendering.  `render.ImageRenderer` is not too bad in my opinion although it's perhaps not ideal.
