### ISSUE TITLE
[FEATURE] Expose the "Bill to" string in invoice.go for customization

### ISSUE THREAD

**Issue by venison** [unidoc/unipdf#333]
**Is your feature request related to a problem? Please describe.**
I'd like to change the "Bill to" string when using `invoice.SetBuyerAddress(...)`  Currently it's a string buried in the implementation of `invoice.generateInformationBlocks(...)`

**Describe the solution you'd like**
Any public method like, SetBuyerHeader or something that would let me set the string to be used.

**Comment by gunnsth** [comment]
Thanks for reporting, we will look into this as well as #332.

**Comment by gunnsth** [comment]
@venison please check PR #334 which addresses this.

**Comment by adrg** [comment]
Here's an example for setting the address heading:
```
invoice.SetBuyerAddress(&creator.InvoiceAddress{
	Heading:   "JANE L MILLER",
	Name:      "MILLER ASSOCIATES",
	Street:    "Suite #134569",
	Street2:   "1960 W CHELSEA AVE STE 2006R",
	City:      "ALLENTOWN",
	State:     "PA",
	Zip:       "18104",
	Separator: " ",
})
```

Also, added `Street2` and `State` fields so it should address issue https://github.com/unidoc/unipdf/issues/332 as well. The Separator field is used to configure the separator between the address components (e.g. street, state, zip). By default, the separator is `, ` in order to maintain backward compatibility.

Output invoice sample: [invoice_simple.pdf](https://github.com/unidoc/unipdf/files/4560686/invoice_simple.pdf).

**Comment by venison** [comment]
That looks great!  Well done!
