### ISSUE TITLE
[BUG] Form Filling does not accomodate page rotation

### ISSUE THREAD

**Issue by AMcPherran** [unidoc/unipdf#352]
## Description
When UniPDF is used to fill the AcroForm on a PDF which has been rotated, the values filled into the fields do not conform to the page's rotation. 

## Expected Behavior
The values filled into a rotated PDF form are rotated to match the orientation of the fields. 

## Actual Behavior
1. Get the `pdf_form_fill_json` example code ready to run ([link](https://github.com/unidoc/unipdf-examples/blob/master/forms/pdf_form_fill_json.go) )
2. Download the attached `90Degrees.pdf` and `90Degrees.json` files, and place them in your `unipdf-examples/forms` directory. 
3. Run `go run pdf_form_fill_json.go 90Degrees.pdf 90Degrees.json Filled90Degrees.pdf` to fill the form. 
4. Open `Filled90Degrees.pdf`, and observe that the text filled into the field does not match the rotation of the page, and may even appear cut off. 
5. Observe similar results with the attached `270Degrees.pdf` + `270Degrees.json`

## Attachments
[90Degrees.pdf](https://github.com/unidoc/unipdf/files/4646649/90Degrees.pdf)
90Degrees.json:
```
[
    {
        "name": "Text4",
        "value": "Testing123!"
    }
]
```
[270Degrees.pdf](https://github.com/unidoc/unipdf/files/4646650/270Degrees.pdf)
270Degrees.json:
```
[
    {
        "name": "Text5",
        "value": "Testing123!"
    }
]
```

**Comment by gunnsth** [comment]
@AMcPherran We are looking at this.  Can you provide similar PDFs with other fields, such as combo boxes, checkboxes too?  A mix of fields including text fields, would be great so we can test those properly.

**Comment by tmlbl** [comment]
Here is a document I created with more field types that is rotated

[FieldTypesRotated.pdf](https://github.com/unidoc/unipdf/files/4767517/FieldTypesRotated.pdf)

**Comment by AMcPherran** [comment]
@gunnsth I tested out the PDF provided by @tmlbl with `v3.8.0` and found that Text fields are all properly rotated now, but the other field types (like the checkbox) are not. I haven't tested the image fields, dropdowns, or radio buttons yet
[FilledFieldTypesRotated.pdf](https://github.com/unidoc/unipdf/files/4795187/FilledFieldTypesRotated.pdf)

**Comment by gunnsth** [comment]
@AMcPherran Did you use the standard example with field appearance set as:
```go
fieldAppearance := annotator.FieldAppearance{OnlyIfMissing: true, RegenerateTextFields: true}
```
Typically correct appearances are already available in forms for static fields such as checkboxes, dropdowns, radio buttons.

I generated the appearance with those default options (as per the example) and in that case the appearance was correct.
[out.pdf](https://github.com/unidoc/unipdf/files/4850174/out.pdf)

Note that text is most important to regenerate since it is most dynamic.  The form creators such as Adobe create desired appearances for all display options for fields with finite number of states (e.g. checkbox: appearance, unchecked appearance).
