### ISSUE TITLE
Checkboxes in an array are not being filled consistently. 

### ISSUE THREAD

**Issue by GalacticGuac** [unidoc/unipdf#466]
## Description
Checkboxes are not being filled consistently on the IRS W9 form. The form has a section of named PDF fields that indicate they are some kind of checkbox array, but only the first box of 8 functions as intended, allowing it to be filled or not with a value of "0" or "1".

## Expected Behavior
All adjacent checkboxes should be filled using the same logic. 

## Actual Behavior
1. Download IRS W9 form from https://www.irs.gov/pub/irs-pdf/fw9.pdf 
2. Use the UniPDF functions to find the field names, and structure the data accordingly
3. User pdfReader.AcroForm.FillWithAppearance() to fill out the data
4. All fields will be filled, except for the checkboxes. Of which, only the first is ever able to be checked. 

## Attachments
Self contained reproduction code:
[checkbox-debug.txt](https://github.com/unidoc/unipdf/files/6858170/checkbox-debug.txt)

Attachment from above link:
[W9.pdf](https://github.com/unidoc/unipdf/files/6858173/W9.pdf)

**Comment by gunnsth** [comment]
The checkboxes check states in W9.pdf file are using indexes, i.e. "1", "2", "3", etc. You can list available states using our example in unipdf-examples/forms/pdf_form_fill_json.go. When you run that example, you should see the checkboxes listed like this:

```
 {
        "name": "topmostSubform[0].Page1[0].FederalClassification[0].c1_1[6]",
        "value": "Off",
        "options": [
            "7",
            "Off"
        ]
    },
```
For above example, one would use "7" as value of field to appear as checked.

So only the first one was working because it had options "1" and "Off", whereas the next one had "2" and "Off" etc.  But the code was putting "1" for those as well.  If an option does not exist, it means it will appear as not checked.
