### ISSUE TITLE
AGPL license that can be used in open source software

### ISSUE THREAD

**Issue by probonopd** [unidoc/unipdf#509]
I am looking to use this in an open source project in accordance with the  "AGPL license that can be used in open source software":

![image](https://user-images.githubusercontent.com/2480569/216174662-5ea9f183-ba5a-4ef7-b3a5-aa800a5607c1.png)

But what is absolutely not acceptable is "confuscated" Go souce code, and phoning home for a "metered liense".

Please let me know how I can use unipdf in an open source project.
Thanks!

**Comment by gunnsth** [comment]
Hi @probonopd

Thank you for reaching out. It's always good to get feedback on possible avenues of future improvement, and I think you raise some important points.

Our mission at UniDoc is to help developers and teams streamline their efforts, and reduce the possible workload that they might have moving forward. It’s to make their lives easier, and alleviate the frustrations they have when working with PDFs and needing to execute specific capabilities that many open-source projects, unfortunately, have gaps with.

It’s not to open everything up as an open-source project. Our customers rely on us for consistent, high-quality Go code that is well-maintained, up-to-date, and stable. And if that’s going to happen, we need to recoup the costs of the investment we’re making every month to stay true to our commitment, and ensure that the applications and infrastructure on which our customers build their business model on don’t fail when they need us the most.

I’m sorry if you’re a bit disappointed in not being able to use our code as you would like.

However, I would take solace in the fact many people would most likely understand the “acceptability” of having obfuscated code in our position.

Not everyone will. And that’s ok. We don't expect to please everyone. And if you need some open-source libraries to help you, here are a few that you might take a look at:
- pdfcpu
- gofpdf

Should you reconsider, you can find full transparency on our pricing at www.unidoc.io/pricing

NOTE: UniPDF was dual-licensed with AGPL/commercial license until version 3.10.0 (in 2020) when it was changed to commercial only with obfuscated. I expect that what you found and mentioned in the issue is from an old commit.

Sincerely,
Gus Hall

**Comment by prochac** [comment]
> Should you reconsider, you can find full transparency on our pricing at www.unidoc.io/pricing

Where is the price? Website shows nothing.

**Comment by probonopd** [comment]
Apparently you need to "Request a Quote" nowadays.

**Comment by ipod4g** [comment]
@prochac 
Thank you for your inquiry regarding our pricing. Our subscriptions are tailored to meet the specific needs of each client and are based on a variety of factors. Rather than offering a one-size-fits-all price, we customize our plans to ensure they align perfectly with your requirements.
While our quotes are personalized, we are open to negotiations. You are welcome to request another quote for a lower-priced plan that matches your specifications. 
Please feel free to contact us directly to discuss your needs in more detail, and we'll be happy to provide you with the best possible pricing options.

**Comment by prochac** [comment]
> Apparently you need to "Request a Quote" nowadays.

Simply means I won't.
