### ISSUE TITLE
[BUG] Not all accented characters are displayed

### ISSUE THREAD

**Issue by vojbarzz** [unidoc/unipdf#87]
## Description
I'm trying to display string containing accented characters `á č ď é ě í ň ó ř š ť ú ů ý ž` but just `á é í ó š ú ý ž` are displayed

## Expected Behavior
All characters of string are displayed: `á č ď é ě í ň ó ř š ť ú ů ý ž`

## Actual Behavior
Only `á é í ó š ú ý ž` characters are displayed

## Attachments
[source and example output](https://github.com/unidoc/unipdf/files/3278726/files.zip)

**Comment by adrg** [comment]
@vojbarzz The standard fonts (which use a standard encoding) do not support those characters. However, you can load a composite font in order to display them. From my tests, the Roboto font in the unipdf repository displays all of the characters correctly. You can find it [here](https://github.com/unidoc/unipdf/tree/master/creator/testdata/roboto).

Here's a modified sample of the code using the mentioned font. I also attached the output PDF ([out.pdf](https://github.com/unidoc/unipdf/files/3586613/out.pdf)).

```


package main

import (
	"log"

	unicommon "github.com/unidoc/unipdf/common"
	"github.com/unidoc/unipdf/creator"
	"github.com/unidoc/unipdf/model"
)

func main() {
	unicommon.SetLogger(unicommon.NewConsoleLogger(unicommon.LogLevelDebug))

	if err := render(); err != nil {
		log.Fatal(err)
	}
	log.Println("Complete, see output file: out.pdf")
}

func render() error {
	font, err := model.NewCompositePdfFontFromTTFFile("path/Roboto-Regular.ttf")
	if err != nil {
		return err
	}

	c := creator.New()
	p := c.NewStyledParagraph()
	p.Append("á č ď é ě í ň ó ř š ť ú ů ý ž").Style.Font = font

	if err := c.Draw(p); err != nil {
		return err
	}
	return c.WriteToFile("out.pdf")
}
```

Also, please make sure you use the development branch of the unipdf repository. I noticed you use the archived unidoc repository in your code sample.
